name: gp_backend
description: A server app using the shelf package and Docker.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  args: ^2.0.0
  shelf: ^1.1.0
  shelf_router: ^1.0.0
  get_it: ^7.2.0
  logger: ^1.1.0
  dotenv: ^3.0.0
  equatable: ^2.0.3
  shelf_hotreload: ^1.0.1
  dio: ^4.0.4
  mongo_dart: ^0.7.4
  html: ^0.15.0
  http: ^0.13.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.15.0
